### ISSUE TITLE
install error in centos 

### ISSUE THREAD

**Issue by orangeSi** [ythuang0522/StriDe#1]
hi,when I run "./autogen.sh" ,I meet an error:
- aclocal
  Use of inherited AUTOLOAD for non-method Autom4te::XFile::msg() is deprecated at /usr/share/autoconf/Autom4te/XFile.pm line 238.
  Can't locate auto/Autom4te/XFile/msg.al in @INC (@INC contains: /usr/share/autoconf /usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.8.8 /usr/lib/perl5/site_perl /usr/lib64/perl5/vendor_perl/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.8.8 /usr/lib/perl5/vendor_perl /usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/5.8.8 .) at /usr/share/autoconf/Autom4te/XFile.pm line 238
  aclocal: autom4te failed with exit status: 1

Thanks!

**Comment by ythuang0522** [comment]
It looks like your issue is probably due to out-of-dated gcc or library. Pls refer to similar post on http://seqanswers.com/forums/showthread.php?t=45610. If it does not work let me know and i will compile a binary version using static linking.

**Comment by orangeSi** [comment]
when I use 
export PATH=/ifs4/BC_PUB/biosoft/pipeline/Package/GCC/gcc_4.9.0/bin:$PATH
export LD_LIBRARY_PATH=/ifs4/BC_PUB/biosoft/pipeline/Package/GCC/gcc_4.9.0/lib:/ifs4/BC_PUB/biosoft/pipeline/Package/GCC/gcc_4.9.0/lib64:$LD_LIBRARY_PATH

but I still get the same error：
Use of inherited AUTOLOAD for non-method Autom4te::XFile::msg() is deprecated at /usr/share/autoconf/Autom4te/XFile.pm line 238.
Can't locate auto/Autom4te/XFile/msg.al in @INC (@INC contains: /usr/share/autoconf /usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.8.8 /usr/lib/perl5/site_perl /usr/lib64/perl5/vendor_perl/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.8.8 /usr/lib/perl5/vendor_perl /usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/5.8.8 .) at /usr/share/autoconf/Autom4te/XFile.pm line 238
aclocal: autom4te failed with exit status: 1

**Comment by orangeSi** [comment]
hi,
after I install automake-1.14 and autoconf-2.65 and use gcc-4.5 ,that error disappear.
then I run "ln -s Makefile.am Makefile.in " ,
then "./configure " is ok.
But "make " say "make: **\* No targets.  Stop."

**Comment by ythuang0522** [comment]
The Makefiles should be generated by first running ./autogen.sh followed by ./configure, instead of creating on your own. I also added a binary version compiled on linux 64bit if your platform is the same.

**Comment by orangeSi** [comment]
The binary say "kernel too old" ,because my platform is CentOS release 5.5 ...
But I compiled it  successfully just now！
